import { createApp } from "vue";
import { Button, Tabbar, TabbarItem, Search, List, Cell, CellGroup, NavBar, Tab, Tabs, Icon, Image as VanImage, Divider, SwipeCell, Skeleton, Form, Field, Loading } from "vant";
import App from "./App.vue";
import router from "./router";
import store from "./store";
import axios from "@/api";
const app = createApp(App);
app.config.$http = axios;
app.use(store);
app.use(router);
// vant 全局组件
app.use(Button);
app.use(Tabbar);
app.use(TabbarItem);
app.use(Search);
app.use(List);
app.use(Cell);
app.use(CellGroup);
app.use(NavBar);
app.use(Tab);
app.use(Tabs);
app.use(Icon);
app.use(VanImage);
app.use(Divider);
app.use(SwipeCell);
app.use(Skeleton);
app.use(Form);
app.use(Field);
app.use(Loading);
app.mount("#app");
